dot_hiv_translations_manager_homepage:
    pattern:  /
    defaults: { _controller: DotHivTranslationsManagerBundle:Default:index }

#dot_hiv_translations_manager_commit:
#    pattern:  /commit
#    defaults: { _controller: DotHivTranslationsManagerBundle:Default:commit }
