dot_hiv_translations_manager_homepage:
    pattern:  /
    defaults: { _controller: DotHivTranslationsManagerBundle:Default:index }

#dot_hiv_translations_manager_csv:
#    pattern:  /csv/{key}
#    defaults: { _controller: DotHivTranslationsManagerBundle:Default:getCsv }
