dot_hiv_translations_manager_homepage:
    pattern:  /
    defaults: { _controller: DotHivTranslationsManagerBundle:Default:index }

dot_hiv_translations_manager_diff:
    pattern:  /diff
    defaults: { _controller: DotHivTranslationsManagerBundle:Default:diff }
