parameters:
    dot_hiv_translations_manager.git.class: DotHiv\TranslationsManagerBundle\Service\GitService

services:
    git:
        class: %dot_hiv_translations_manager.git.class%
        arguments: [%gitrepo%,%gitremote%]
