parameters:
#    dot_hiv_translations_manager.example.class: DotHiv\TranslationsManagerBundle\Example

services:
#    dot_hiv_translations_manager.example:
#        class: %dot_hiv_translations_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
